### ISSUE TITLE
Unecessery import

### ISSUE THREAD

**Issue by PatBoulay** [Wizcorp/cordova-plugin-yanap#11]
In your file LoopPlayer.java, there is an import: import org.chromium.base.Log;

It seems to be not necessary because I dont have this package so I remove the line to be able to compile.

**Comment by tbrebant** [comment]
You are totally right! Sorry for having been long to answer. Will do a PR to fix that.

**Comment by PatBoulay** [comment]
No problem, I did it from my side.


Pat

________________________________
De : Brebant <notifications@github.com>
Envoyé : mardi 6 décembre 2016 20:24:44
À : Wizcorp/cordova-plugin-yanap
Cc : PatBoulay; Author
Objet : Re: [Wizcorp/cordova-plugin-yanap] Unecessery import (#11)


You are totally right! Sorry for having been long to answer. Will do a PR to fix that.

-

**Comment by tbrebant** [comment]
Fixed by https://github.com/Wizcorp/cordova-plugin-yanap/commit/63c0cd40360e3eaa0061c4816058ff3fef0a3768 in version [0.8.10](https://github.com/Wizcorp/cordova-plugin-yanap/tree/0.8.10).
